name: PR_auto

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Run tests for the org linter inside DevContainer
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/cheld/org-devcontainer
        cacheFrom: ghcr.io/cheld/org-devcontainer
        runCmd: ./tests/run-test.sh